In [32]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv("salary_data.csv")

In [36]:
df.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [38]:
df.isnull().sum()

Experience Years    0
Salary              0
dtype: int64

In [40]:
df

    Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [63]:
X = df[['Experience Years']]
Y = df[['Salary']]

In [65]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [67]:
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [69]:
prediction = model.predict(X_test)

In [71]:
r2 = r2_score(Y_test,prediction)
r2

0.9068577573647874

In [73]:
mse = mean_squared_error(Y_test, prediction)
rmse = np.sqrt(mse)
rmse

6933.810724932834

In [94]:
def model_checking():
    exp = float(input("enter experience; "))
    
    user_data = pd.DataFrame({'Experience Years' : [exp]})
    pred = float(model.predict(user_data)[0])
    print("-" * 35)
    print(f"Predicted Salary for {exp} years of experience is {pred:,.2f}")
    print("-" * 35)

model_checking()

enter experience;  12

-----------------------------------
Predicted Salary for 12.0 years of experience is 139,612.63
-----------------------------------

C:\Users\HP\AppData\Local\Temp\ipykernel_24352\3465959959.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  pred = float(model.predict(user_data)[0])